In [22]:
import numpy as np
import pandas as pd
import os



In [23]:
df = pd.read_csv('placement.csv')
df.head()

,Unnamed: 0,cgpa,iq,placement
0,0,6.8,123.0,1
1,1,5.9,106.0,0
2,2,5.3,121.0,0
3,3,7.4,132.0,1
4,4,5.8,142.0,0


In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  100 non-null    int64  
 1   cgpa        100 non-null    float64
 2   iq          100 non-null    float64
 3   placement   100 non-null    int64  
dtypes: float64(2), int64(2)
memory usage: 3.3 KB


In [25]:
df.shape

(100, 4)

In [26]:
df = df.iloc[:, 1:]

In [27]:
df.head()

,cgpa,iq,placement
0,6.8,123.0,1
1,5.9,106.0,0
2,5.3,121.0,0
3,7.4,132.0,1
4,5.8,142.0,0


In [28]:
import matplotlib.pylab as plt

ModuleNotFoundError: No module named 'matplotlib.pylab'

In [ ]:
plt.scatter(df[df['placement']==1]['cgpa'],
            df[df['placement']==1]['iq'],
            color='green',
            label='Yes')

plt.scatter(df[df['placement']==0]['cgpa'],
            df[df['placement']==0]['iq'],
            color='red',
            label='No')

plt.xlabel('CGPA')
plt.ylabel('IQ')
plt.legend()
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\praja\\AppData\\Roaming\\Python\\Python314\\site-packages\\matplotlib\\mpl-data\\fonts\\ttf\\LastResortHE-Regular.ttf'

<Figure size 640x480 with 1 Axes>

In [ ]:
X = df.iloc[:, 0:2]
Y = df.iloc[:,-1]
print(X)
print("Shape of X: ",X.shape)
print(Y)
print("Shape of Y: ",Y.shape)

    cgpa     iq
0    6.8  123.0
1    5.9  106.0
2    5.3  121.0
3    7.4  132.0
4    5.8  142.0
..   ...    ...
95   4.3  200.0
96   4.4   42.0
97   6.7  182.0
98   6.3  103.0
99   6.2  113.0

[100 rows x 2 columns]
Shape of X:  (100, 2)
0     1
1     0
2     0
3     1
4     0
     ..
95    0
96    0
97    1
98    1
99    1
Name: placement, Length: 100, dtype: int64
Shape of Y:  (100,)


# Train test split 

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_text, Y_train, Y_text = train_test_split(X,Y,test_size=0.1)

In [ ]:
X_train

,cgpa,iq
90,7.3,86.0
38,6.5,160.0
3,7.4,132.0
60,6.9,139.0
27,6.0,124.0
...,...,...
76,4.9,155.0
0,6.8,123.0
57,6.5,130.0
62,6.0,102.0


In [ ]:
X_text

,cgpa,iq
66,6.9,96.0
64,7.0,64.0
74,6.7,154.0
72,7.3,116.0
30,7.6,128.0
26,7.0,199.0
84,5.7,169.0
81,5.4,107.0
52,7.0,175.0
16,5.2,224.0


In [ ]:
Y_train

90    1
38    1
3     1
60    1
27    1
     ..
76    0
0     1
57    1
62    0
34    0
Name: placement, Length: 90, dtype: int64

In [ ]:
Y_text

66    1
64    1
74    1
72    1
30    1
26    1
84    0
81    0
52    1
16    0
Name: placement, dtype: int64

# Scale the Test Splits

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

In [ ]:
X_train

array([[ 1.19353459, -0.92623621],
       [ 0.49883378,  1.00996378],
       [ 1.28037219,  0.27734757],
       [ 0.84618418,  0.46050162],
       [ 0.06464577,  0.06802865],
       [ 1.01985939,  0.77448   ],
       [ 0.93302178,  0.46050162],
       [-0.97740545,  0.51283135],
       [-0.89056785, -1.58035783],
       [ 0.41199618,  0.51283135],
       [-1.41159345,  2.05655837],
       [-0.45637984,  0.35584216],
       [-1.75894386, -0.32444432],
       [ 0.41199618, -0.14129027],
       [-0.89056785, -0.03663081],
       [ 1.01985939, -1.92050107],
       [ 0.75934658,  0.51283135],
       [ 0.06464577, -1.99899567],
       [ 1.8882354 ,  0.72215027],
       [ 1.36720979,  0.95763405],
       [-0.97740545,  1.24544756],
       [-0.63005504,  1.03612864],
       [-1.67210626, -0.55992811],
       [ 0.67250898,  1.5855908 ],
       [-2.27996947,  1.61175567],
       [-0.63005504,  0.27734757],
       [-0.63005504, -0.29827946],
       [ 0.75934658, -0.24594973],
       [-0.71689264,

In [ ]:
X_text = scaler.fit_transform(X_text)
X_text 

array([[ 0.40393223, -1.00136735],
       [ 0.53016106, -1.68026047],
       [ 0.15147459,  0.22912643],
       [ 0.90884753, -0.57705915],
       [ 1.28753399, -0.32247423],
       [ 0.53016106,  1.18381988],
       [-1.11081364,  0.54735758],
       [-1.48950011, -0.76799784],
       [ 0.53016106,  0.67465004],
       [-1.74195776,  1.71420512]])

# Model Training

In [ ]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train, Y_train)

NameError: name 'X_train' is not defined

In [ ]:
clf.predict(X_text)

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 0])

In [ ]:
Y_text

66    1
64    1
74    1
72    1
30    1
26    1
84    0
81    0
52    1
16    0
Name: placement, dtype: int64

In [ ]:
Y_pred = clf.predict(X_text)
Y_pred 

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 0])

In [ ]:
# Accuracy Score

from sklearn.metrics import accuracy_score

accuracy_score(Y_text, Y_pred)

1.0

In [ ]:

from mlxtend.plotting import plot_decision_regions

In [ ]:
plot_decision_regions(X_train, Y_train.values, clf=clf, legend=2)

<Axes: >

Error in callback <function _draw_all_if_interactive at 0x000001AED3DC4CA0> (for post_execute), with arguments args (),kwargs {}:


FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\praja\\AppData\\Roaming\\Python\\Python314\\site-packages\\matplotlib\\mpl-data\\fonts\\ttf\\LastResortHE-Regular.ttf'

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\praja\\AppData\\Roaming\\Python\\Python314\\site-packages\\matplotlib\\mpl-data\\fonts\\ttf\\LastResortHE-Regular.ttf'

<Figure size 640x480 with 1 Axes>

In [ ]:
import pickle

In [29]:
pickle.dump(clf,open('model.pkl', 'wb'))