In [1]:
import numpy as np

In [ ]:
# 0D Tensor/Scalar (ndim)
a = np.array(4)
a.ndim

0

**1D Tensor/Vector** --> A list of numbers along one axis.</br>
Common use:</br>
    Feature vector</br>
    Word embedding

In [ ]:
arr = np.array([1,2,3,4])  
print(arr) # 4 vector
print(arr.ndim)


[1 2 3 4] 1


**2D Tensor/Martices** --> Rows and columns.</br>
Common use:</br>
    Spreadsheet-like data</br>
    Grayscale images (height × width)

In [ ]:
mat = np.array([[2,4,5], [5,6,7], [8,9,1]])
print(mat)
mat.ndim

[[2 4 5]
 [5 6 7]
 [8 9 1]]


2

**3D Tensor** --> A stack of matrices.</br>
Common use:</br>
RGB image: (height, width, channels)</br>
Sequence data</br>

**4D Tensor** --> A collection (batch) of 3D tensors.</br>
Common use:</br>
Deep learning mini-batches</br>

**5D Tensor** --> A collection of 4D tensors.</br>
Common use:</br>
Video processing</br>
Medical imaging (multiple scans over time) </br>

**ND tensor** --> A tensor with any number of dimensions N

In [ ]:
# ND Tensors
NDmat = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[8,9,7],[6,4,5],[4,2,3]], [[5,9,7],[8,1,3],[0,4,2]]])
print(NDmat)
NDmat.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[8 9 7]
  [6 4 5]
  [4 2 3]]

 [[5 9 7]
  [8 1 3]
  [0 4 2]]]


3